#DEBUG=y

SOURCES= c_analys.c c_dcbias.c c_difmag.c c_dyptrk.c c_energy.c c_framin.c \
	c_glob.c c_hp100.c c_ini.c c_invert.c c_ivfilt.c c_lpc10.c c_lpf31.c \
	c_mload.c c_onset.c c_placea.c c_placev.c c_preemp.c c_rcchk.c \
	c_shift.c c_tbdm.c c_voice.c c_vparms.c d_bsynz.c d_deemp.c d_glob.c \
	d_ini.c d_irc2pc.c d_lpc10.c d_pitsyn.c d_random.c d_synths.c \
	lpc10_c1.c lpc10_c2.c lpc10_d1.c lpc10_d2.c pthl10.c r1_dec.c \
	r1_ham84.c r1_med.c r1_recv.c r2_dec.c r2_recv.c r_uquant.c s1_send.c \
	s2_send.c s_quant.c sr1_glob.c sr_glob.c

INCLUDES=-I../include -I../../sys/include 

FLAGS=


include ../../make.rul
