#DEBUG=y

SOURCES= chrono.c clargs.c eta.cpp string.cpp wrkbuff.c\
		uti_file.c uti_misc.c uti_path.c uti_str.c xalloc.c \
		uti_math.c uti_end.c listt.cpp listt_0.cpp listt_1.cpp \
		listt_2.cpp strl.cpp strl_0.cpp strl_1.cpp strl_2.cpp \
		strl_3.cpp  uti_die.c

INCLUDES=-I../include -I../../spl/include

FLAGS=

include ../../make.rul

