#DEBUG=y

SOURCES=codec.c spl0.c spl1.c spl2.c spl3.c spl4.c spl5a.c spl5b.c spl5c.c \
		spl5d.c spl5e.c spl6.c spl7.c spl8a.c spl8b.c spl8c.c spl9.c spl10.c \
		stat.c xfft1.c xfft2.c xfft3.c xfft4.c vad.cpp lpcroots.cpp zroots.cpp \
		cbuffer.cpp deltas.cpp

INCLUDES=-I../include -I../../sys/include

FLAGS=


include ../../make.rul

