# DEBUG=y

SOURCES=afaho1.cpp afaho2.cpp afauto.cpp afraw.cpp aftei.cpp \
	aftxh.cpp cabctrl.c cabecer.c caudiof.cpp fblock.cpp fvblk.c \
	fvoz.c samp.cpp caudio.cpp afwav.cpp afwav_0.cpp afwav_1.cpp \
	afnist.cpp afhak.cpp mark.cpp mark_0.cpp mark_1.cpp mark_2.cpp \
	mark_3.cpp samp_0.cpp

INCLUDES=-I../include -I../../sys/include -I../../spl/include

FLAGS=


include ../../make.rul
